---
name: CI

on:
  pull_request:
    branches:
      - main
      - development
  push:
    branches:
      - main
      - development
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  build-and-test-v5:
    name: Build and Test V5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: "18"
      - name: Install dependencies
        run: cd Tasks/TerraformTask/TerraformTaskV5 && npm install --include=dev
      - name: Lint
        run: cd Tasks/TerraformTask/TerraformTaskV5 && npx eslint src/
      - name: Compile TypeScript
        run: cd Tasks/TerraformTask/TerraformTaskV5 && npm run compile
      - name: Run unit tests
        run: cd Tasks/TerraformTask/TerraformTaskV5 && npm test

  build-and-test-installer-v1:
    name: Build and Test Installer V1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
        with:
          node-version: "18"
      - name: Install dependencies
        run: cd Tasks/TerraformInstaller/TerraformInstallerV1 && npm install --include=dev
      - name: Lint
        run: cd Tasks/TerraformInstaller/TerraformInstallerV1 && npx eslint src/
      - name: Compile TypeScript
        run: cd Tasks/TerraformInstaller/TerraformInstallerV1 && npm run compile
      - name: Run unit tests
        run: cd Tasks/TerraformInstaller/TerraformInstallerV1 && npm test
